variables:
  IsLightBuild: $[eq(variables['Build.Reason'], 'PullRequest')]
  IsCanaryBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries/')]

jobs:
- job: Windows
  strategy:
    maxParallel: 3
    matrix:
      Android:
        Project: Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
        ApplicationPlatform: AnyCPU
        ArtifactName: Android
      SkiaGTK:
        Project: Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
        ApplicationPlatform: AnyCPU
        ArtifactName: SkiaGTK
      UWP:
        Project: Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
        ApplicationPlatform: x64
        ArtifactName: UWP
  pool:
    vmImage: windows-2019
  
  steps:
    - template: build/stage-build.yml

- job: macOS
  strategy:
    maxParallel: 2
    matrix:
      iOS:
        Project: Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
        ApplicationPlatform: iPhone
        ArtifactName: iOS
      macOS:
        Project: Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
        ApplicationPlatform: iPhoneSimulator
        ArtifactName: macOS
  pool:
    vmImage: macOS-10.15
    
  variables:
  - name: SkipUnknownFrameworks
    value: true # Used by TargetFrameworks.Filtering package
  - group: apple.appstore.distribution # Variables for certificate

  steps:
  - task: InstallAppleCertificate@2
    displayName: Install Certificate
    inputs:
      certSecureFile: apple.appstore.distribution.p12
      certPwd: $(appleappstorecertificatepassword)
      keychain: temp
      deleteCert: true
  
  - task: InstallAppleProvisioningProfile@1
    displayName: Install Provisioning Profile
    inputs:
      provisioningProfileLocation: secureFiles
      provProfileSecureFile: UnoGallery.mobileprovision

  - template: build/stage-build.yml

- job: Linux
  pool:
    vmImage: ubuntu-18.04
  
  container: unoplatform/wasm-build:3.0

  variables:
    ArtifactName: WASM
    SkipUnknownFrameworks: true

  steps:
    - template: build/stage-build-wasm.yml
